### ISSUE TITLE
Contrasting colors for adjacent annotations

### ISSUE THREAD

**Issue by jowch** [Wong-Lab/caliban#1]
**Is your feature request related to a problem? Please describe.**
It is difficult to visually inspect annotations and identify errors quickly when the colors for adjacent labels are so similar as is currently the case.

**Describe the solution you'd like**
Adjacent cells should have different colors!

**Describe alternatives you've considered**
Currently, the only reasonable way to find mislabeled adjacent cells is to cycle through the labels in highlighting mode. This can be short-circuited with the suggested change.

**Additional context**
Here is a list of relevant code sections:
- `helper_update_composite()`
  https://github.com/Wong-Lab/caliban/blob/65f57d3c25180e6ed813d60539018326e9ab8a6d/desktop/caliban.py#L1359-L1364
- `__init__()`
  https://github.com/Wong-Lab/caliban/blob/65f57d3c25180e6ed813d60539018326e9ab8a6d/desktop/caliban.py#L187

**Comment by calboi91** [comment]
If we're going to edit this, would it make sense to get a list of unique labels and iterate color based on that rather than the label values themselves? This was one of the issues in their original repo. For example, in the current code, labels 1-20 will have a different color than labels 101-120, even though both are just 20 labels.

**Comment by jowch** [comment]
Wouldn't that mean even more changes to Caliban in terms of how its numbering works? It makes some assumptions about the numbering within a target stack (crop in our case). I think their assumption does have the benefit of making numbering consistent within a chunk. For example, how would you handle the case where we add an id (ie. 121). Would you add it as 1 or 121? There is no way for Caliban to know the global state of numbering so we would have to renumber at stitch time anyways.

As of now I have this (modified from [this Gist](https://gist.github.com/jgomezdans/402500))
```python
vals = np.linspace(0,1,256)
np.random.default_rng().shuffle(vals)
self.labels_cmap = plt.cm.colors.ListedColormap(plt.cm.viridis(vals))
```

This just randomly shuffles the colormap so that adjacent ids will on average get a different color. I suppose there is no guarantee that the colors will be very different.

**Comment by calboi91** [comment]
My idea was more for the colormap display. The labels themselves would not be touched. Currently, I think a new ID is determined by taking the max of all the labels + 1. 

I suppose a simple shuffle of the colormap is the easiest solution.

**Comment by jowch** [comment]
I'm in the process of testing it. I'll post some screenshots and we can go from there.

**Comment by jowch** [comment]
I would say generally it's much better, but there are still some adjacents with similar colors.

| Before | After |
|- |-	|
| ![Screen Shot 2020-10-15 at 6 31 23 PM](https://user-images.githubusercontent.com/19571703/96202769-eb842280-0f14-11eb-95d5-bd8200abffdf.png) | ![Screen Shot 2020-10-15 at 6 17 01 PM](https://user-images.githubusercontent.com/19571703/96202787-f6d74e00-0f14-11eb-8a6c-dfe3cbf0bfad.png) |
